print('Instucciones para subir a GitHub desde la terminal:')
print('..................................................')
print('1. Desplazar al directorio del repositorio ')
print('2. Clonar el repositorio, solo si no se encuentra en el ordedor')
print('3. Preguntar el estado local con git status')
print('4. Preguntar el estado del repositorio en github.com aplicando la instruccion: git remote show origin')
print('5. Actualizar repositorio en ordenador con git pull origin master')
print('6. Agregar archivos git add . ')
print('7. Ejecutar git commit -m "mensaje"')
print('8. Ejcutar git push origin master')
